FROM ghcr.io/rubyonracetracks/image-debian-<SUITE>-min-stage1

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/winner/web-filter

COPY . .

RUN sudo chown -R winner:winner /home/winner/web-filter && \
    cd /home/winner/web-filter && bin/main
