name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '21 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CODE_NAME: ['bookworm']

    env:
      SUITE: ${{ matrix.CODE_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Provision
        run: bin/provision

      - name: Run web-filter
        run: bash test-ci.sh
