name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '21 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the web filtering script
        run: bash main.sh
