name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '21 5 * * *'

inputs:
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the web filtering script
        run: bash main.sh
